local M = {}

M.INVENTORY_START_INDEX = 0
M.INVENTORY_END_INDEX = 8
M.INVENTORY_SIZE = 9

M.STASH_START_INDEX = 9
M.STASH_END_INDEX = 14
M.STASH_SIZE = 6

M.MAX_UNIT_SEARCH_RADIUS = 2000
M.MAX_UNIT_TARGET_RADIUS = 1600

M.TREE_SEARCH_RADIUS = 1000
M.CREEP_AGRO_RADIUS = 400

M.MIN_CREEP_DISTANCE = 250
M.BASE_CREEP_DISTANCE = 270
M.MAX_CREEP_DISTANCE = 710

M.MAX_PURSUE_DISTANCE = 1000

M.MAX_CREEP_ATTACK_RANGE = 690
M.MAX_TOWER_ATTACK_RANGE = 730
M.MAX_HERO_ATTACK_RANGE = 765 -- with the dragon lance item
M.MAX_MELEE_ATTACK_RANGE = 310

M.UNIT_LOW_HEALTH_LEVEL = 0.3 -- 30%
M.UNIT_LOW_HEALTH = 250
M.UNIT_HALF_HEALTH_LEVEL = 0.5 -- 50%

M.DROW_RANGER_ATTACK_POINT = 0.7

M.TURN_TARGET_MAX_DEGREE = 11.5

return M
