local M = {}

M.INVENTORY_START_INDEX = 0
M.INVENTORY_END_INDEX = 8
M.INVENTORY_SIZE = 9

M.STASH_START_INDEX = 9
M.STASH_END_INDEX = 14
M.STASH_SIZE = 6

M.MAP_LOCATION_RADIUS = 500

M.DEFAULT_ABILITY_USAGE_RADIUS = 600
M.MAX_ABILITY_USAGE_RADIUS = 1600

M.CREEP_AGRO_RADIUS = 500
M.MIN_CREEP_DISTANCE = 300
M.TURN_CREEP_DISTANCE = 350
M.MAX_CREEP_DISTANCE = 700
M.MAX_CREEP_ATTACK_RANGE = 690
M.MAX_TOWER_ATTACK_RANGE = 700
M.MAX_HERO_ATTACK_RANGE = 700

return M
